# Generated by Django 6.0.1 on 2026-01-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='AI_two_Chatting',
            field=models.JSONField(default=list),
        ),
    ]
