# Generated by Django 6.0.1 on 2026-01-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_ai_two_chatting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='AI_three_Chatting',
            field=models.JSONField(default=list),
        ),
    ]
