# Generated by Django 6.0 on 2025-12-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="genre",
            field=models.CharField(default="액션", max_length=100),
        ),
        migrations.AddField(
            model_name="reviews",
            name="score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="reviews",
            name="title",
            field=models.CharField(default="스파이더맨", max_length=100),
        ),
        migrations.AddField(
            model_name="reviews",
            name="year",
            field=models.IntegerField(default=2025),
        ),
    ]
