# Generated by Django 6.0 on 2025-12-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_reviews_genre_reviews_score_reviews_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="director",
            field=models.CharField(default="empty", max_length=30),
        ),
        migrations.AddField(
            model_name="reviews",
            name="hero",
            field=models.CharField(default="empty", max_length=100),
        ),
        migrations.AddField(
            model_name="reviews",
            name="running_time",
            field=models.CharField(default="empty", max_length=100),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="genre",
            field=models.CharField(default="empty", max_length=100),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="title",
            field=models.CharField(default="empty", max_length=100),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="year",
            field=models.IntegerField(default=0),
        ),
    ]
