# Generated by Django 6.0 on 2025-12-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0003_reviews_director_reviews_hero_reviews_running_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="opinion",
            field=models.CharField(default="empty", max_length=100),
        ),
    ]
