# Generated by Django 6.0 on 2025-12-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0004_reviews_opinion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="opinion",
            field=models.TextField(default="empty"),
        ),
    ]
