# Generated by Django 6.0 on 2025-12-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0005_alter_reviews_opinion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="running_time",
            field=models.IntegerField(default=0),
        ),
    ]
