# Generated by Django 6.0 on 2025-12-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0006_alter_reviews_running_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviews",
            old_name="running_time",
            new_name="running_hour",
        ),
        migrations.AddField(
            model_name="reviews",
            name="running_minute",
            field=models.IntegerField(default=0),
        ),
    ]
