# Generated by Django 6.0 on 2025-12-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0007_rename_running_time_reviews_running_hour_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="running_total",
            field=models.IntegerField(default=0),
        ),
    ]
