# Generated by Django 6.0.1 on 2026-01-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_reviews_running_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
