# Generated by Django 6.0.1 on 2026-01-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_reviews_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='isTMDB',
            field=models.BooleanField(default=True),
        ),
    ]
