# Generated by Django 6.0.1 on 2026-01-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_reviews_istmdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='movie_id',
            field=models.IntegerField(default=0),
        ),
    ]
