# Generated by Django 4.2.27 on 2026-01-02 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idea", "0002_idea_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="interest",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
