# Generated by Django 6.0 on 2026-01-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_alter_idea_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devtool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='empty_name', max_length=30)),
                ('kind', models.CharField(default='empty_kind', max_length=30)),
                ('content', models.TextField(default='empty_content')),
            ],
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(default='empty_title', max_length=30),
        ),
    ]
