# Generated by Django 6.0 on 2026-01-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_devtool_alter_idea_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='devtool',
        ),
        migrations.AddField(
            model_name='idea',
            name='devtools',
            field=models.ManyToManyField(related_name='ideas', to='idea.devtool'),
        ),
    ]
