# Generated by Django 6.0 on 2026-01-02 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0005_remove_idea_devtool_idea_devtools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='devtools',
        ),
        migrations.AddField(
            model_name='idea',
            name='devtool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideas', to='idea.devtool'),
        ),
    ]
