# Generated by Django 4.2.27 on 2026-01-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0006_remove_idea_devtools_idea_devtool'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='zzim',
            field=models.BooleanField(default=False),
        ),
    ]
