# Generated by Django 5.2.4 on 2026-01-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_carbohydrate_post_fat_post_kcal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="carbohydrate",
            field=models.IntegerField(verbose_name="탄수화물(g)"),
        ),
        migrations.AlterField(
            model_name="post",
            name="fat",
            field=models.FloatField(verbose_name="지방(g)"),
        ),
        migrations.AlterField(
            model_name="post",
            name="kcal",
            field=models.IntegerField(verbose_name="칼로리 정보(Kcal)"),
        ),
        migrations.AlterField(
            model_name="post",
            name="protein",
            field=models.IntegerField(verbose_name="단백질(g)"),
        ),
    ]
