# Generated by Django 5.2.4 on 2026-01-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_carbohydrate_alter_post_fat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='carbohydrate',
            field=models.FloatField(verbose_name='탄수화물(g)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='kcal',
            field=models.FloatField(verbose_name='칼로리 정보(Kcal)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='protein',
            field=models.FloatField(verbose_name='단백질(g)'),
        ),
    ]
