# Generated by Django 6.0 on 2026-01-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="empty_title", max_length=100)),
                ("content", models.TextField(default="empty_content")),
                (
                    "interest",
                    models.CharField(default="empty_interest", max_length=100),
                ),
                ("devtool", models.CharField(default="empty_devtool", max_length=100)),
            ],
        ),
    ]
