# Generated by Django 6.0 on 2026-01-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idea", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
