# Generated by Django 6.0.1 on 2026-01-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_alter_comment_user_alter_post_user_alter_story_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='posts/%y/%m/%d/'),
        ),
    ]
