# Generated by Django 6.0.1 on 2026-01-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_remove_post_joayo_post_joayo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='content',
        ),
        migrations.AddField(
            model_name='story',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='posts/%y/%m/%d/'),
        ),
    ]
